### ISSUE TITLE
[Feature] Support nested todos items

### ISSUE THREAD

**Issue by seanlowe** [joeriddles/extended-task-lists#14]
Hello, came across your plugin in an attempt to find something to collate all my various todo's throughout my vault.

Is it possible to have it so that any checkboxes that have nested checkboxes display as such on the generated list? I tend to group my todos in chunks and so having them all just display in the same order means I lose quite a bit of context on them.

Thanks!

**Comment by joeriddles** [comment]
Hey @seanlowe, thanks for creating this issue! I will work on adding this! Expect to see a new release soon!

**Comment by joeriddles** [comment]
It looks like right now the tasks are added, but are not nested.

<img width="451" alt="image" src="https://github.com/joeriddles/extended-task-lists/assets/19392916/4f5eaedc-88b9-4123-9949-626ee880140d">

<img width="394" alt="image" src="https://github.com/joeriddles/extended-task-lists/assets/19392916/df119066-db0c-4ab2-8302-8da8519ed0aa">

**Comment by seanlowe** [comment]
Yeah, I noticed that I was getting a lot of todos but it was all in one list and as such I was confused.. more of a "I don't remember what this todo is about" and it wasn't until I opened the file and realized they were all nested that they made sense.

**Comment by joeriddles** [comment]
@seanlowe I just released an update: https://github.com/joeriddles/extended-task-lists/releases/tag/1.0.8

Please update the plugin and see if it works the way you expect it.

In my local testing, it looks like it messed up some formatting. I will work on a follow-up fix.

**Comment by seanlowe** [comment]
Looks great! Thanks a ton!!
